import { useId, type Ref } from "react";
import type { ReceiptViewModel } from "./viewModel";
import "./receipt.css";

interface ReceiptPaperProps {
  vm: ReceiptViewModel;
  /** Optional ref forwarded to the .receipt-paper element so callers
   * (e.g. the export pipeline) can capture it directly. */
  paperRef?: Ref<HTMLDivElement>;
}

export function ReceiptPaper({ vm, paperRef }: ReceiptPaperProps) {
  const empty = vm.hero.totalTokensRaw === 0 && vm.items.length === 0;
  // Unique per-instance ID so preview + export root (both render <ReceiptPaper>)
  // don't collide on the same SVG pattern id in the DOM.
  const scallopId = `receipt-scallop-${useId()}`;
  return (
    <div className="receipt-stage">
      <div className="receipt-paper" ref={paperRef}>
        <header className="receipt__header">
          <div className="receipt__brand">BUSYTOK</div>
          <div className="receipt__subtitle">AI CODING · TOKEN RECEIPT</div>
        </header>

        <div className="receipt__divider" />

        <div className="receipt__meta">
          <span>{vm.dateLabel}</span>
          <span>{vm.peakHour ? `PEAK ${vm.peakHour}` : "PEAK —"}</span>
          <span>RECEIPT {vm.serial}</span>
          <span>TZ {vm.timezone}</span>
        </div>

        {empty ? (
          <div className="receipt-paper__empty">No usage recorded for this day.</div>
        ) : (
          <>
            <div className="receipt__divider" />
            <section className="receipt__hero">
              <div className="receipt__hero-value">{vm.hero.totalTokens}</div>
              <div className="receipt__hero-label">TOTAL TOKENS</div>
              <div className="receipt__hero-secondary">
                <span>{vm.secondary.split}</span>
                <span>{vm.secondary.cost} · cache hit {vm.secondary.cacheHitRate}</span>
              </div>
            </section>

            <div className="receipt__divider" />
            <section>
              <div className="receipt__items-header">ITEMS</div>
              {vm.items.map((item) => (
                <div
                  key={item.name}
                  className={`receipt__item${item.others ? " receipt__item--others" : ""}`}
                >
                  <span className="receipt__item-name">{item.name}</span>
                  <span className="receipt__item-value">
                    <span className="receipt__item-tokens">{item.tokens}</span>
                    <span className="receipt__item-cost">{item.cost}</span>
                  </span>
                </div>
              ))}
            </section>

            <div className="receipt__total">
              <span>TOTAL</span>
              <span className="receipt__total-value">
                <span>{vm.total.tokens} tok</span>
                <span className="receipt__total-cost">{vm.total.cost}</span>
              </span>
            </div>

            <div className="receipt__stamp">LOCAL AUDIT</div>
          </>
        )}

        <footer className="receipt__footer">
          <div>NO PROMPTS UPLOADED</div>
          <div>LOCAL AUDIT ONLY</div>
          <div>generated by busytok · /busytok</div>
          <div className="receipt__barcode" aria-hidden="true" />
        </footer>

        {/* Capture-safe scalloped bottom edge (CSS mask is unreliable in
            foreignObject capture). */}
        <svg className="receipt__tear" width="420" height="14" aria-hidden="true">
          <defs>
            <pattern id={scallopId} width="20" height="14" patternUnits="userSpaceOnUse">
              <path d="M0,4 H20 a10,10 0 0,1 -20,0 Z" fill="#f6efe2" />
            </pattern>
          </defs>
          <rect width="420" height="14" fill={`url(#${scallopId})`} />
        </svg>
      </div>
    </div>
  );
}
