import { useId, type Ref } from "react";
import type { ReceiptViewModel } from "./viewModel";
import "./receipt.css";

interface ReceiptPaperProps {
  vm: ReceiptViewModel;
  /** Optional ref forwarded to the .receipt-paper element so callers
   * (e.g. the export pipeline) can capture it directly. */
  paperRef?: Ref<HTMLDivElement>;
}

export function ReceiptPaper({ vm, paperRef }: ReceiptPaperProps) {
  const empty = vm.totalTokensRaw === 0 && vm.items.length === 0;
  // Unique per-instance ID so preview + export root (both render <ReceiptPaper>)
  // don't collide on the same SVG pattern id in the DOM.
  const scallopId = `receipt-scallop-${useId()}`;
  return (
    <div className="receipt-paper" ref={paperRef}>
      <header className="receipt__header">
        <div className="receipt__brand">BUSYTOK</div>
        <div className="receipt__subtitle">AI CODING · TOKEN RECEIPT</div>
      </header>

      <div className="receipt__divider" />

      <div className="receipt__meta">
        <span>{vm.dateLabel}</span>
        <span>ISSUED {vm.generatedAtLabel}</span>
      </div>

      <div className="receipt__body">
        {empty ? (
          <div className="receipt-paper__empty">No usage recorded for this day.</div>
        ) : (
          <>
            <section className="receipt__items">
              <div className="receipt__items-header">
                <span>ITEM</span>
                <span>TOKENS</span>
                <span>COST</span>
              </div>
              {vm.items.map((item) => (
                <div key={item.name} className="receipt__item">
                  <span className="receipt__item-name">{item.name}</span>
                  <span className="receipt__item-tokens">{item.tokens}</span>
                  <span className="receipt__item-cost">{item.cost}</span>
                </div>
              ))}
              {vm.truncated && (
                <div className="receipt__items-truncated" aria-hidden="true">
                  · · ·
                </div>
              )}
            </section>

            <div className="receipt__total">
              <span className="receipt__total-label">TOTAL</span>
              <span className="receipt__total-tokens">{vm.total.tokens}</span>
              <span className="receipt__total-cost">{vm.total.cost}</span>
            </div>
          </>
        )}
      </div>

      {/* Footer: in/out/cache split + cache hit rate, then centered QR,
          then the brand line in typewriter face. */}
      <footer className="receipt__footer">
        {!empty && (
          <div className="receipt__footer-stats">
            <span>{vm.summary}</span>
            <span>cache hit {vm.cacheHitRate}</span>
          </div>
        )}
        <img
          className="receipt__qr"
          src="/busytok-gh-qr.svg"
          alt="Scan to open busytok on GitHub"
          width="56"
          height="56"
        />
        <div className="receipt__footer-brand">generated by busytok · /busytok</div>
      </footer>

      {/* Capture-safe scalloped bottom edge (CSS mask is unreliable in
          foreignObject capture). */}
      <svg className="receipt__tear" width="420" height="14" aria-hidden="true">
        <defs>
          <pattern id={scallopId} width="20" height="14" patternUnits="userSpaceOnUse">
            <path d="M0,4 H20 a10,10 0 0,1 -20,0 Z" fill="#f6efe2" />
          </pattern>
        </defs>
        <rect width="420" height="14" fill={`url(#${scallopId})`} />
      </svg>
    </div>
  );
}
