import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import { ReceiptPaper } from "./ReceiptPaper";
import { toReceiptViewModel } from "./viewModel";
import {
  MANY_MODELS,
  LONG_NAMES,
  NO_DATA,
  NORMAL_DAY,
  OTHERS_ALL_UNAVAILABLE,
  OTHERS_MIXED_COST,
  PARTIAL_COST,
  ZERO_COST,
} from "./fixtures";

afterEach(() => cleanup());

function renderVm(dto = NORMAL_DAY) {
  return render(<ReceiptPaper vm={toReceiptViewModel(dto)} />);
}

describe("ReceiptPaper", () => {
  it("renders brand, ITEMS, TOTAL, and footer with summary stats", () => {
    renderVm();
    expect(screen.getByText("DAILY AI CODING BILL")).toBeDefined();
    expect(screen.getByText("ITEM")).toBeDefined();
    expect(screen.getByText("TOTAL")).toBeDefined();
    expect(screen.getByText("TOKEN BREAKDOWN")).toBeDefined();
    expect(screen.getByText(/CACHE HIT/)).toBeDefined();
    // Meta row carries date + PRINTED time only (no RECEIPT #serial).
    expect(screen.getByText(/PRINTED \d{2}:\d{2}/)).toBeDefined();
    expect(screen.queryByText(/RECEIPT #/)).toBeNull();
  });

  it("does NOT render the old oversized TOTAL TOKENS hero block", () => {
    const { container } = renderVm();
    expect(screen.queryByText("TOTAL TOKENS")).toBeNull();
    expect(container.querySelector(".receipt__hero")).toBeNull();
  });

  it("renders the privacy trust line and subtitle", () => {
    renderVm();
    expect(screen.getByText("LOCAL-FIRST · NO PROMPTS UPLOADED")).toBeDefined();
    expect(screen.getByText("AI CODING · TOKEN RECEIPT")).toBeDefined();
    expect(screen.queryByText("generated by busytok")).toBeNull();
  });

  it("renders a frameless QR block with SCAN TO STAR ON GITHUB + short URL", () => {
    const { container } = renderVm();
    // No white-box stamp (removed — broke paper continuity).
    expect(container.querySelector(".receipt__qr-stamp")).toBeNull();
    const block = container.querySelector(".receipt__qr-block");
    expect(block).not.toBeNull();
    // QR image inside the block.
    const qr = block?.querySelector(".receipt__qr");
    expect(qr).not.toBeNull();
    expect(qr?.tagName).toBe("IMG");
    expect(qr?.getAttribute("src")).toBe("/busytok-gh-qr.svg");
    // CTA + short URL.
    expect(block?.querySelector(".receipt__qr-hint")?.textContent).toBe(
      "SCAN TO STAR ON GITHUB",
    );
    expect(block?.querySelector(".receipt__qr-url")?.textContent).toBe(
      "github.com/BalianWang/busytok",
    );
    // Old wrappers are gone.
    expect(container.querySelector(".receipt__qr-stamp")).toBeNull();
    expect(container.querySelector(".receipt__qr-row")).toBeNull();
    expect(container.querySelector(".receipt__qr-cta")).toBeNull();
    expect(container.querySelector(".receipt__barcode")).toBeNull();
    expect(container.querySelector(".receipt__footer-stats")).toBeNull();
  });

  it("caps ITEMS at 5 rows and shows a truncation indicator when there are >5 models", () => {
    // MANY_MODELS has 8 models → top 5 shown, overflow 3 elided.
    const { container } = renderVm(MANY_MODELS);
    const itemRows = container.querySelectorAll(".receipt__item");
    expect(itemRows.length).toBe(5);
    // Old OTHERS aggregate row is gone.
    expect(screen.queryByText(/OTHERS/)).toBeNull();
    // Truncation indicator renders.
    const indicator = container.querySelector(".receipt__items-truncated");
    expect(indicator).not.toBeNull();
    expect(indicator?.textContent?.trim()).toBe("· · ·");
  });

  it("does NOT show the truncation indicator when ≤5 models", () => {
    const { container } = renderVm(); // NORMAL_DAY has 1 model
    expect(container.querySelector(".receipt__items-truncated")).toBeNull();
  });

  it("truncates and shows the indicator when overflow models are all unavailable", () => {
    // OTHERS_ALL_UNAVAILABLE: top 5 exact; overflow (2 unavailable) elided.
    // The truncation indicator is the only signal that overflow existed.
    const { container } = renderVm(OTHERS_ALL_UNAVAILABLE);
    expect(container.querySelector(".receipt__items-truncated")).not.toBeNull();
    // Top-5 item rows all render (no OTHERS row).
    expect(container.querySelectorAll(".receipt__item").length).toBe(5);
  });

  it("truncates and shows the indicator when overflow models are mixed", () => {
    // OTHERS_MIXED_COST: overflow mixed (1 exact + 1 unavailable), elided.
    // The TOTAL block still carries the aggregate cost from the full set.
    const { container } = renderVm(OTHERS_MIXED_COST);
    expect(container.querySelector(".receipt__items-truncated")).not.toBeNull();
    expect(screen.getByText("TOTAL")).toBeDefined();
  });

  it("marks partial aggregate cost with ≈ and keeps exact item cost plain", () => {
    renderVm(PARTIAL_COST);
    expect(screen.getByText("≈$47.21")).toBeDefined(); // TOTAL block
    expect(screen.getByText("$24.10")).toBeDefined(); // exact-status item row
    expect(screen.getAllByText("—").length).toBeGreaterThan(0); // unavailable item
  });

  it("shows the empty state when there are no models and no tokens", () => {
    const { container } = renderVm(NO_DATA);
    expect(container.querySelector(".receipt-paper__empty")).not.toBeNull();
    expect(screen.getByText(/PRINTED —/)).toBeDefined();
  });

  it("does not render the breakdown band on empty state", () => {
    const { container } = renderVm(NO_DATA);
    expect(container.querySelector(".receipt__breakdown")).toBeNull();
    expect(container.querySelector(".receipt__footer-brand")).not.toBeNull();
    expect(container.querySelector(".receipt__qr")).not.toBeNull();
  });

  it("renders 'CACHE HIT --' when cache_hit_rate is null but tokens exist", () => {
    renderVm(ZERO_COST);
    expect(screen.getByText(/CACHE HIT --/)).toBeDefined();
    expect(screen.getByText("TOTAL")).toBeDefined();
  });

  it("truncates long model names", () => {
    renderVm(LONG_NAMES);
    const name = screen.getByText(/claude-sonnet-4-5-thinking-very-long/);
    expect(name).toBeDefined();
  });

  it("aligns ITEMS and TOTAL on the same three-column structure", () => {
    const { container } = renderVm();
    const itemRows = container.querySelectorAll(".receipt__item");
    const totalRow = container.querySelector(".receipt__total");
    expect(itemRows.length).toBeGreaterThan(0);
    expect(totalRow).not.toBeNull();
    const itemChildren = Array.from(itemRows[0].children);
    const totalChildren = Array.from(totalRow!.children);
    expect(itemChildren.length).toBe(3);
    expect(totalChildren.length).toBe(3);
    const itemRoles = itemChildren.map((c) => c.className);
    const totalRoles = totalChildren.map((c) => c.className);
    expect(itemRoles[0]).toBe("receipt__item-name");
    expect(itemRoles[1]).toBe("receipt__item-tokens");
    expect(itemRoles[2]).toBe("receipt__item-cost");
    expect(totalRoles[0]).toBe("receipt__total-label");
    expect(totalRoles[1]).toBe("receipt__total-tokens");
    expect(totalRoles[2]).toBe("receipt__total-cost");
  });

  it("does not render timezone or PEAK labels (removed per spec)", () => {
    renderVm();
    expect(screen.queryByText(/PEAK/)).toBeNull();
    expect(screen.queryByText(/TZ/)).toBeNull();
  });

  it("renders the paper with a flex body wrapper (fixed 3:4, 420 × 560)", () => {
    const { container } = renderVm();
    const paper = container.querySelector(".receipt-paper") as HTMLElement;
    expect(paper).not.toBeNull();
    // jsdom does not resolve external CSS, so we assert the DOM contract:
    // the body region exists as the flex:1 absorber that keeps the footer
    // pinned to the bottom. The CSS rule (receipt.css) sets height:560px
    // (fixed 3:4) — safe now because items are capped at TOP_N=5 rows.
    const body = container.querySelector(".receipt__body");
    expect(body).not.toBeNull();
  });

  it("does NOT render the brand stamp (removed from default template)", () => {
    const { container } = renderVm();
    expect(container.querySelector(".receipt-stamp")).toBeNull();
  });
});
