import { describe, expect, it } from "vitest";

import defaultCapabilityRaw from "../src-tauri/capabilities/default.json?raw";
import desktopHostRetryShortcutRegistrationPermissionRaw from "../src-tauri/permissions/autogenerated/desktop_host_retry_shortcut_registration.toml?raw";
import desktopHostShortcutDiagnosticsPermissionRaw from "../src-tauri/permissions/autogenerated/desktop_host_shortcut_diagnostics.toml?raw";
import desktopHostShowGuiPermissionRaw from "../src-tauri/permissions/autogenerated/desktop_host_show_gui.toml?raw";
import flushFrontendLogsPermissionRaw from "../src-tauri/permissions/autogenerated/flush_frontend_logs.toml?raw";
import invokeBusytokPermissionRaw from "../src-tauri/permissions/autogenerated/invoke_busytok.toml?raw";
import logFrontendEventPermissionRaw from "../src-tauri/permissions/autogenerated/log_frontend_event.toml?raw";
import promptPaletteAccessibilityStatusPermissionRaw from "../src-tauri/permissions/autogenerated/prompt_palette_accessibility_status.toml?raw";
import promptPaletteOpenAccessibilitySettingsPermissionRaw from "../src-tauri/permissions/autogenerated/prompt_palette_open_accessibility_settings.toml?raw";
import promptPalettePasteActiveAppPermissionRaw from "../src-tauri/permissions/autogenerated/prompt_palette_paste_active_app.toml?raw";

const mainWindowCommands = {
  invoke_busytok: invokeBusytokPermissionRaw,
  log_frontend_event: logFrontendEventPermissionRaw,
  flush_frontend_logs: flushFrontendLogsPermissionRaw,
  prompt_palette_paste_active_app: promptPalettePasteActiveAppPermissionRaw,
  prompt_palette_accessibility_status:
    promptPaletteAccessibilityStatusPermissionRaw,
  prompt_palette_open_accessibility_settings:
    promptPaletteOpenAccessibilitySettingsPermissionRaw,
  desktop_host_shortcut_diagnostics: desktopHostShortcutDiagnosticsPermissionRaw,
  desktop_host_retry_shortcut_registration:
    desktopHostRetryShortcutRegistrationPermissionRaw,
  desktop_host_show_gui: desktopHostShowGuiPermissionRaw,
} as const;

function commandPermission(command: string): string {
  return `allow-${command.replaceAll("_", "-")}`;
}

describe("Tauri capabilities", () => {
  it("allows every main-window command used by the frontend", () => {
    const capability = JSON.parse(defaultCapabilityRaw) as {
      permissions: string[];
    };

    for (const command of Object.keys(mainWindowCommands)) {
      const permission = commandPermission(command);
      expect(capability.permissions, `${command} must be allowed`).toContain(
        permission,
      );
    }
  });

  it("has generated command permissions for every main-window command", () => {
    for (const [command, raw] of Object.entries(mainWindowCommands)) {
      expect(raw).toContain(`commands.allow = ["${command}"]`);
    }
  });
});
