#![allow(clippy::unwrap_used)]

use busytok_subagent::SubagentError;

/// Exercise every `code()` arm so the dispatcher's stable error mapping is
/// fully covered. These codes are the contract the control layer matches on.
#[test]
fn error_code_covers_all_variants() {
    assert_eq!(
        SubagentError::NotFound("x".into()).code(),
        "subagent.not_found"
    );
    assert_eq!(
        SubagentError::AmbiguousName("x".into()).code(),
        "subagent.ambiguous_name"
    );
    assert_eq!(
        SubagentError::InvalidName("x".into()).code(),
        "subagent.invalid_name"
    );
    assert_eq!(
        SubagentError::ProfileNotFound("x".into()).code(),
        "subagent.profile_not_found"
    );
    assert_eq!(SubagentError::Disabled.code(), "subagent.disabled");
    assert_eq!(
        SubagentError::Store(anyhow::anyhow!("boom")).code(),
        "subagent.store_error"
    );
}

/// Display impls (generated by thiserror) should surface the inner message.
#[test]
fn error_display_carries_context() {
    assert_eq!(
        SubagentError::NotFound("abc".into()).to_string(),
        "logical subagent not found: abc"
    );
    assert_eq!(
        SubagentError::Disabled.to_string(),
        "subagent feature is disabled"
    );
    assert!(SubagentError::Store(anyhow::anyhow!("disk full"))
        .to_string()
        .contains("database error"));
}
