#![allow(clippy::unwrap_used)]

use busytok_subagent::SubagentError;

/// Exercise every `code()` arm so the dispatcher's stable error mapping is
/// fully covered. These codes are the contract the control layer matches on.
#[test]
fn error_code_covers_all_variants() {
    assert_eq!(
        SubagentError::NotFound("x".into()).code(),
        "subagent.not_found"
    );
    assert_eq!(
        SubagentError::AmbiguousName("x".into()).code(),
        "subagent.ambiguous_name"
    );
    assert_eq!(
        SubagentError::InvalidName("x".into()).code(),
        "subagent.invalid_name"
    );
    assert_eq!(
        SubagentError::InvalidArgument("x".into()).code(),
        "subagent.invalid_argument"
    );
    assert_eq!(
        SubagentError::ProfileNotFound("x".into()).code(),
        "subagent.profile_not_found"
    );
    assert_eq!(SubagentError::Disabled.code(), "subagent.disabled");
    assert_eq!(
        SubagentError::Store(anyhow::anyhow!("boom")).code(),
        "subagent.store_error"
    );
    // Sidecar (Plan 2) variants — these were previously uncovered.
    assert_eq!(SubagentError::TaskTimeout.code(), "subagent.task_timeout");
    assert_eq!(
        SubagentError::SidecarSpawn("x".into()).code(),
        "subagent.sidecar_spawn_failed"
    );
    assert_eq!(
        SubagentError::SidecarRpc("x".into()).code(),
        "subagent.sidecar_rpc_error"
    );
    assert_eq!(
        SubagentError::SidecarIo("x".into()).code(),
        "subagent.sidecar_io_error"
    );
    assert_eq!(
        SubagentError::SidecarTimeout("x".into()).code(),
        "subagent.sidecar_timeout"
    );
    assert_eq!(
        SubagentError::SidecarCrashed("x".into()).code(),
        "subagent.sidecar_crashed"
    );
}

/// Display impls (generated by thiserror) should surface the inner message.
#[test]
fn error_display_carries_context() {
    assert_eq!(
        SubagentError::NotFound("abc".into()).to_string(),
        "logical subagent not found: abc"
    );
    assert_eq!(
        SubagentError::Disabled.to_string(),
        "subagent feature is disabled"
    );
    assert!(SubagentError::Store(anyhow::anyhow!("disk full"))
        .to_string()
        .contains("database error"));
}
