#![allow(clippy::unwrap_used)]

use busytok_subagent::SubagentError;

/// Exercise every `code()` arm so the dispatcher's stable error mapping is
/// fully covered. These codes are the contract the control layer matches on.
#[test]
fn error_code_covers_all_variants() {
    assert_eq!(
        SubagentError::NotFound("x".into()).code(),
        "subagent.not_found"
    );
    assert_eq!(
        SubagentError::AmbiguousName("x".into()).code(),
        "subagent.ambiguous_name"
    );
    assert_eq!(
        SubagentError::InvalidName("x".into()).code(),
        "subagent.invalid_name"
    );
    assert_eq!(
        SubagentError::InvalidArgument("x".into()).code(),
        "subagent.invalid_argument"
    );
    assert_eq!(
        SubagentError::ProfileNotFound("x".into()).code(),
        "subagent.profile_not_found"
    );
    assert_eq!(SubagentError::Disabled.code(), "subagent.disabled");
    assert_eq!(
        SubagentError::Store(anyhow::anyhow!("boom")).code(),
        "subagent.store_error"
    );
    // Sidecar (Plan 2) variants — these were previously uncovered.
    assert_eq!(SubagentError::TaskTimeout.code(), "subagent.task_timeout");
    assert_eq!(
        SubagentError::SidecarSpawn("x".into()).code(),
        "subagent.sidecar_spawn_failed"
    );
    assert_eq!(
        SubagentError::SidecarRpc {
            message: "x".into(),
            code: None
        }
        .code(),
        "subagent.sidecar_rpc_error"
    );
    assert_eq!(
        SubagentError::SidecarIo("x".into()).code(),
        "subagent.sidecar_io_error"
    );
    assert_eq!(
        SubagentError::SidecarTimeout("x".into()).code(),
        "subagent.sidecar_timeout"
    );
    assert_eq!(
        SubagentError::SidecarCrashed("x".into()).code(),
        "subagent.sidecar_crashed"
    );
    assert_eq!(
        SubagentError::HotSessionLimit {
            candidate: "sess_abc".into()
        }
        .code(),
        "subagent.hot_session_limit"
    );
}

/// Display impls (generated by thiserror) should surface the inner message.
#[test]
fn error_display_carries_context() {
    assert_eq!(
        SubagentError::NotFound("abc".into()).to_string(),
        "logical subagent not found: abc"
    );
    assert_eq!(
        SubagentError::Disabled.to_string(),
        "subagent feature is disabled"
    );
    assert!(SubagentError::Store(anyhow::anyhow!("disk full"))
        .to_string()
        .contains("database error"));
}

/// FailingTaskExecutor must always return an error carrying the reason,
/// AND the error must downcast to `SubagentError::SidecarSpawn` so the
/// control layer surfaces `subagent.sidecar_spawn_failed` (not the generic
/// `subagent.store_error`). This preserves the RPC error contract.
#[tokio::test]
async fn failing_executor_always_errors() {
    use busytok_subagent::mock_executor::{ExecutorInput, FailingTaskExecutor, TaskExecutor};
    use busytok_subagent::SubagentError;

    let exec = FailingTaskExecutor {
        reason: "bundle not found".to_string(),
    };
    let input = ExecutorInput {
        subagent_id: "test".into(),
        subagent_name: "test".into(),
        cwd: "/tmp".into(),
        profile: "pi/search-cheap".into(),
        model: None,
        prompt: "do".into(),
        prompt_artifact_ref: None,
        timeout_seconds: None,
        tools: vec![],
        memory: busytok_subagent::context::MemorySnapshot {
            hot_summary: None,
            long_summary: None,
            key_files: vec![],
            decisions: vec![],
            open_questions: vec![],
        },
        context: busytok_subagent::context::CompactContext {
            compact_context: String::new(),
            budget_tokens: 0,
            source: String::new(),
        },
        write_access: false,
        provider_id: None,
    };
    let err = match exec.execute(&input).await {
        Ok(_) => panic!("FailingTaskExecutor must always fail"),
        Err(e) => e,
    };
    // The error MUST downcast to SubagentError::SidecarSpawn so the manager
    // preserves the semantic error code through the RPC contract.
    let sub_err = err
        .downcast::<SubagentError>()
        .expect("error must downcast to SubagentError::SidecarSpawn");
    assert_eq!(sub_err.code(), "subagent.sidecar_spawn_failed");
    match sub_err {
        SubagentError::SidecarSpawn(msg) => {
            assert!(
                msg.contains("bundle not found"),
                "error should carry the reason, got: {msg}"
            );
        }
        other => panic!("expected SidecarSpawn, got {other:?}"),
    }
}
