/// Generate TypeScript type definitions and write them to the frontend package.
#[cfg(test)]
mod tests {
    use crate::dto;
    use std::fs;
    use std::path::PathBuf;
    use ts_rs::TS;

    fn workspace_root() -> PathBuf {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        manifest_dir
            .parent()
            .expect("crate dir has parent")
            .parent()
            .expect("crates dir has parent")
            .to_path_buf()
    }

    #[test]
    fn generate_typescript_types() {
        let out_dir = workspace_root()
            .join("packages")
            .join("busytok-protocol-types")
            .join("src");

        fs::create_dir_all(&out_dir).expect("create generated dir");

        let mut ts = String::new();
        ts.push_str("// Auto-generated by busytok-protocol — DO NOT EDIT\n");
        ts.push_str("// Run: cargo test -p busytok-protocol generate_typescript_types\n\n");
        ts.push_str("export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };\n\n");
        ts.push_str(
            "export type RequestMeta = { session_id: string | null, correlation_id: string | null, };\n\n",
        );

        // Collect type exports in dependency order
        let type_defs: Vec<String> = vec![
            dto::ControlRequest::decl(),
            dto::ControlError::decl(),
            dto::ControlResponse::decl(),
            dto::ServiceHealthDto::decl(),
            dto::ServiceStatusDto::decl(),
            // Shared DTOs
            dto::RangePresetDto::decl(),
            dto::ToneDto::decl(),
            dto::ActivityStatusDto::decl(),
            dto::CostStatusDto::decl(),
            dto::WeekdayIndexDto::decl(),
            dto::SourceTypeDto::decl(),
            dto::StatusActionDto::decl(),
            dto::SeverityDto::decl(),
            dto::MetricOptionDto::decl(),
            dto::MethodErrorDto::<serde_json::Value>::decl(),
            dto::TrendBucketGranularityDto::decl(),
            dto::BreakdownKindDto::decl(),
            dto::SourceScanStateDto::decl(),
            dto::SettingsValidationErrorCodeDto::decl(),
            dto::SettingsRecoveryActionIdDto::decl(),
            // Shell and Overview DTOs
            dto::StatusChipDto::decl(),
            dto::ShellStatusDto::decl(),
            dto::OverviewMetricDto::decl(),
            dto::OverviewTrendBucketDto::decl(),
            dto::OverviewTrendDto::decl(),
            dto::OverviewRankingItemDto::decl(),
            dto::OverviewRankingSectionDto::decl(),
            dto::OverviewHeatmapDayDto::decl(),
            dto::OverviewHeatmapDto::decl(),
            // Activity DTOs
            dto::ActivityListRequestDto::decl(),
            dto::ActivityListSummaryDto::decl(),
            dto::ActivityListItemDto::decl(),
            dto::ActivityListResponseDto::decl(),
            dto::ActivityDetailRequestDto::decl(),
            dto::TokenBreakdownDto::decl(),
            dto::ActivityTechnicalDetailsDto::decl(),
            dto::ActivityDetailDto::decl(),
            // Breakdown DTOs
            dto::BreakdownListRequestDto::decl(),
            dto::ProjectBreakdownListItemDto::decl(),
            dto::ModelBreakdownListItemDto::decl(),
            dto::SessionBreakdownListItemDto::decl(),
            dto::BreakdownListItemDto::decl(),
            dto::BreakdownListResponseSummaryDto::decl(),
            dto::BreakdownListResponseDto::decl(),
            dto::BreakdownDetailRequestDto::decl(),
            dto::BreakdownMiniItemDto::decl(),
            dto::TechnicalDetailDto::decl(),
            dto::ProjectBreakdownDetailDto::decl(),
            dto::ModelBreakdownDetailDto::decl(),
            dto::SessionTimelineItemDto::decl(),
            dto::SourceContextItemDto::decl(),
            dto::SessionBreakdownDetailDto::decl(),
            dto::BreakdownDetailDto::decl(),
            // Clients DTOs
            dto::ClientsSnapshotRequestDto::decl(),
            dto::ClientStatusCardDto::decl(),
            dto::ClientSourceRowDto::decl(),
            dto::ClientsSnapshotSummaryDto::decl(),
            dto::ClientsSnapshotDto::decl(),
            dto::ClientSourceDetailRequestDto::decl(),
            dto::ClientSourceDetailDto::decl(),
            // Settings DTOs
            dto::ManualRootDto::decl(),
            dto::SettingsDiscoveryDto::decl(),
            dto::SettingsPrivacyDto::decl(),
            dto::SettingsDiagnosticsDto::decl(),
            dto::SubagentDoctorResultDto::decl(),
            dto::DoctorCheckDto::decl(),
            dto::SettingsDiagnosticEventDto::decl(),
            dto::SettingsRecoveryActionDto::decl(),
            dto::SettingsRecoveryActionRequestDto::decl(),
            dto::SettingsRecoveryActionResponseDto::decl(),
            dto::SettingsValidationErrorDto::decl(),
            dto::SettingsSnapshotDto::decl(),
            dto::SettingsUpdateRequestDto::decl(),
            // Prompt Palette DTOs
            dto::PromptActionDto::decl(),
            dto::PromptSortDto::decl(),
            dto::PromptUseSurfaceDto::decl(),
            dto::PromptUseOutcomeDto::decl(),
            dto::PromptUseFailureReasonDto::decl(),
            dto::PromptEntryDto::decl(),
            dto::PromptListQueryDto::decl(),
            dto::PromptListResponseDto::decl(),
            dto::PromptGetRequestDto::decl(),
            dto::PromptCreateRequestDto::decl(),
            dto::PromptUpdateRequestDto::decl(),
            dto::PromptDeleteRequestDto::decl(),
            dto::PromptDeleteResultDto::decl(),
            dto::PromptUseRequestDto::decl(),
            dto::PromptUseResultDto::decl(),
            dto::PromptSuggestTagsRequestDto::decl(),
            dto::PromptSuggestTagsResponseDto::decl(),
            // Invalidation types
            dto::InvalidationDatasetDto::decl(),
            dto::InvalidationScopeDto::decl(),
            // Live types
            dto::LiveSampleDto::decl(),
            // New modular DTOs (envelope, readiness, scan progress)
            dto::ReadinessStateDto::decl(),
            dto::ScanProgressDto::decl(),
            dto::ReadEnvelopeDto::<serde_json::Value>::decl(),
            // Overview modular DTOs
            dto::OverviewSummaryRequestDto::decl(),
            dto::OverviewSummaryDto::decl(),
            dto::OverviewTrendRequestDto::decl(),
            dto::OverviewTrendResponseDto::decl(),
            dto::OverviewHeatmapRequestDto::decl(),
            dto::OverviewHeatmapResponseDto::decl(),
            dto::OverviewRankingsRequestDto::decl(),
            dto::OverviewRankingsResponseDto::decl(),
            // Activity modular DTOs
            dto::ActivityRecentRequestDto::decl(),
            dto::ActivityRecentResponseDto::decl(),
            // Live window DTO
            dto::LiveWindowRequestDto::decl(),
            dto::LiveWindowDto::decl(),
            // Event sequence state
            dto::EventSequenceStateDto::decl(),
            // Event streaming types
            dto::RuntimeEventDto::decl(),
            dto::EventSubscriptionBatchDto::decl(),
            // Subagent control DTOs (subagent.* methods)
            dto::SubagentUsageDto::decl(),
            dto::SubagentDelegateResponseDto::decl(),
            dto::SubagentResolveRequestDto::decl(),
            dto::SubagentDelegateRequestDto::decl(),
            dto::SubagentListRequestDto::decl(),
            dto::SubagentDetailDto::decl(),
            dto::SubagentListResponseDto::decl(),
            dto::SubagentTaskSummaryDto::decl(),
            dto::SubagentTasksRequestDto::decl(),
            dto::SubagentTasksResponseDto::decl(),
            dto::SubagentDeleteRequestDto::decl(),
            dto::SubagentAckDto::decl(),
            // Receipt (daily share image)
            dto::ReceiptPeakHourDto::decl(),
            dto::ReceiptModelSliceDto::decl(),
            dto::ReceiptBrandDto::decl(),
            dto::ReceiptMetricsDto::decl(),
            dto::ReceiptDailyRequestDto::decl(),
            dto::ReceiptDailyDto::decl(),
            // Provider (credential foundation)
            dto::ProviderDto::decl(),
            dto::ProviderCreateRequestDto::decl(),
            dto::ProviderUpdateRequestDto::decl(),
            dto::ProviderListResponseDto::decl(),
            dto::ProviderDeleteRequestDto::decl(),
            dto::ProviderTestConnectionRequestDto::decl(),
            dto::ProviderTestConnectionResponseDto::decl(),
        ]
        .into_iter()
        .collect();

        ts.push_str(
            &type_defs
                .join("\n\n")
                .replace("type ", "export type ")
                .replace("bigint", "number"),
        );
        ts.push('\n');

        let out_path = out_dir.join("generated.ts");
        fs::write(&out_path, ts).expect("write generated.ts");

        // Also update index.ts to re-export generated types
        let index_path = out_dir.join("index.ts");
        let index_content = "// Busytok protocol types\nexport * from './generated.js';\n";
        fs::write(&index_path, index_content).expect("write index.ts");
    }
}
