// Auto-generated by busytok-protocol — DO NOT EDIT
// Run: cargo test -p busytok-protocol generate_typescript_types

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type RequestMeta = { session_id: string | null, correlation_id: string | null, };

export type ControlRequest = { method: string, params: JsonValue, meta: RequestMeta, };

export type ControlError = { code: string, message: string, payload: JsonValue | null, };

export type ControlResponse = { "Ok": JsonValue } | { "Err": ControlError };

export type ServiceHealthDto = { ready: boolean, db_healthy: boolean, scan_state: string, };

export type ServiceStatusDto = { version: string, db_path: string, state: string, };

export type RangePresetDto = "day" | "week" | "month" | "year";

export type ToneDto = "neutral" | "success" | "warning" | "danger";

export type ActivityStatusDto = "ok" | "warning" | "error";

export type CostStatusDto = "exact" | "partial" | "unavailable";

export type WeekdayIndexDto = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type SourceTypeDto = "default_discovery" | "manual_root";

export type StatusActionDto = "open_activity" | "open_settings";

export type SeverityDto = "info" | "warning" | "error";

export type MetricOptionDto = "tokens" | "cost";

export type MethodErrorDto<TPayload = JsonValue> = { code: string, message: string, payload: TPayload | null, };

export type TrendBucketGranularityDto = "hour" | "day" | "week" | "month";

export type BreakdownKindDto = "project" | "model" | "session";

export type SourceScanStateDto = "idle" | "scanning" | "warning" | "error";

export type SettingsValidationErrorCodeDto = "invalid_timezone" | "invalid_week_starts_on" | "invalid_client_id" | "invalid_source_type" | "invalid_root_path" | "duplicate_manual_root";

export type SettingsRecoveryActionIdDto = "rescan_all" | "rebuild_rollups" | "reset_failed_checkpoints";

export type StatusChipDto = { id: string, label: string, tone: ToneDto, detail: string | null, action: StatusActionDto | null, };

export type ShellStatusDto = { generated_at_ms: number, status_chips: Array<StatusChipDto>, readiness: ReadinessStateDto, latest_event_seq: number | null, writer_queue_depth: number | null, aggregate_lag_ms: number | null, subscription_bridge_connectivity: string | null, };

export type OverviewMetricDto = { id: string, label: string, value: string, helper: string | null, tone: ToneDto, };

export type OverviewTrendBucketDto = { key: string, label: string, start_ms: number, end_ms: number, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, event_count: number, is_current: boolean, };

export type OverviewTrendDto = { range: RangePresetDto, bucket_granularity: TrendBucketGranularityDto, metric_options: Array<MetricOptionDto>, cost_status: CostStatusDto, buckets: Array<OverviewTrendBucketDto>, };

export type OverviewRankingItemDto = { id: string, label: string, value: string, helper: string | null, bar_value: number, action: StatusActionDto | null, };

export type OverviewRankingSectionDto = { id: string, title: string, items: Array<OverviewRankingItemDto>, };

export type OverviewHeatmapDayDto = { date: string, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, event_count: number, };

export type OverviewHeatmapDto = { today: string, week_starts_on: WeekdayIndexDto, days: Array<OverviewHeatmapDayDto>, };

export type ActivityListRequestDto = { range: RangePresetDto, cursor: string | null, limit: number | null, client_id: string | null, source_id: string | null, project_hash: string | null, model_id: string | null, };

export type ActivityListSummaryDto = { item_count: number, total_tokens: number, total_cost_usd: number | null, cost_status: CostStatusDto, };

export type ActivityListItemDto = { id: string, happened_at_ms: number, client_id: string, client_label: string, source_id: string | null, source_label: string | null, source_root_path: string | null, project_label: string | null, project_hash: string | null, model_id: string | null, model_label: string | null, tokens: number, cache_hit_rate: number | null, cost_usd: number | null, cost_status: CostStatusDto, status: ActivityStatusDto, detail_available: boolean, };

export type ActivityListResponseDto = { generated_at_ms: number, items: Array<ActivityListItemDto>, next_cursor: string | null, summary: ActivityListSummaryDto, };

export type ActivityDetailRequestDto = { id: string, };

export type TokenBreakdownDto = { prompt_input_total_tokens: number | null, prompt_input_non_cached_tokens: number | null, cache_read_tokens: number | null, cache_write_tokens: number | null, cache_hit_rate: number | null, input_tokens: number | null, output_tokens: number | null, cached_input_tokens: number | null, reasoning_tokens: number | null, total_tokens: number, };

export type ActivityTechnicalDetailsDto = { source_id: string | null, provider: string | null, raw_model: string | null, notes: Array<string>, };

export type ActivityDetailDto = { id: string, title: string, subtitle: string | null, happened_at_ms: number, client_id: string, client_label: string, source_id: string | null, source_label: string | null, source_root_path: string | null, project_label: string | null, project_hash: string | null, session_id: string | null, model_id: string | null, model_label: string | null, status: ActivityStatusDto, tokens: number, token_breakdown: TokenBreakdownDto | null, cost_usd: number | null, cost_status: CostStatusDto, technical_details: ActivityTechnicalDetailsDto, };

export type BreakdownListRequestDto = { kind: BreakdownKindDto, range: RangePresetDto, cursor: string | null, limit: number | null, };

export type ProjectBreakdownListItemDto = { id: string, project_hash: string, label: string, subtitle: string | null, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, event_count: number, last_active_at_ms: number | null, top_model_label: string | null, };

export type ModelBreakdownListItemDto = { id: string, label: string, subtitle: string | null, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, event_count: number, last_active_at_ms: number | null, client_labels: Array<string>, top_project_label: string | null, };

export type SessionBreakdownListItemDto = { id: string, label: string, subtitle: string | null, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, event_count: number, last_active_at_ms: number | null, client_label: string, project_label: string | null, project_hash: string | null, };

export type BreakdownListItemDto = { "kind": "project" } & ProjectBreakdownListItemDto | { "kind": "model" } & ModelBreakdownListItemDto | { "kind": "session" } & SessionBreakdownListItemDto;

export type BreakdownListResponseSummaryDto = { item_count: number, total_tokens: number, total_cost_usd: number | null, total_cost_status: CostStatusDto, };

export type BreakdownListResponseDto = { generated_at_ms: number, kind: BreakdownKindDto, items: Array<BreakdownListItemDto>, next_cursor: string | null, summary: BreakdownListResponseSummaryDto, };

export type BreakdownDetailRequestDto = { kind: BreakdownKindDto, id: string, range: RangePresetDto, };

export type BreakdownMiniItemDto = { id: string, label: string, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, event_count: number, };

export type TechnicalDetailDto = { label: string, value: string, };

export type ProjectBreakdownDetailDto = { id: string, label: string, project_hash: string, project_path: string | null, metrics: Array<OverviewMetricDto>, trend: OverviewTrendDto, model_mix: Array<BreakdownMiniItemDto>, sessions: Array<SessionBreakdownListItemDto>, recent_activity: Array<ActivityListItemDto>, technical_details: Array<TechnicalDetailDto>, };

export type ModelBreakdownDetailDto = { id: string, label: string, metrics: Array<OverviewMetricDto>, trend: OverviewTrendDto, token_breakdown: TokenBreakdownDto, client_mix: Array<BreakdownMiniItemDto>, project_mix: Array<ProjectBreakdownListItemDto>, recent_activity: Array<ActivityListItemDto>, technical_details: Array<TechnicalDetailDto>, };

export type SessionTimelineItemDto = { id: string, happened_at_ms: number, label: string, tokens: number, cost_usd: number | null, cost_status: CostStatusDto, status: ActivityStatusDto, };

export type SourceContextItemDto = { source_id: string, client_label: string, root_path: string, };

export type SessionBreakdownDetailDto = { id: string, label: string, client_id: string, client_label: string, project_label: string | null, project_hash: string | null, last_active_at_ms: number | null, metrics: Array<OverviewMetricDto>, token_breakdown: TokenBreakdownDto, timeline: Array<SessionTimelineItemDto>, models_used: Array<BreakdownMiniItemDto>, source_context: Array<SourceContextItemDto>, technical_details: Array<TechnicalDetailDto>, };

export type BreakdownDetailDto = { "kind": "project" } & ProjectBreakdownDetailDto | { "kind": "model" } & ModelBreakdownDetailDto | { "kind": "session" } & SessionBreakdownDetailDto;

export type ClientsSnapshotRequestDto = { cursor: string | null, limit: number | null, client_id: string | null, scan_state: SourceScanStateDto | null, };

export type ClientStatusCardDto = { id: string, label: string, tone: ToneDto, active_source_count: number, event_count: number, last_scan_at_ms: number | null, helper: string | null, };

export type ClientSourceRowDto = { id: string, client_id: string, client_label: string, root_path: string, source_type: SourceTypeDto, scan_state: SourceScanStateDto, configured_by_user: boolean, last_scan_at_ms: number | null, file_count: number, parsed_file_count: number, event_count: number, last_error: string | null, };

export type ClientsSnapshotSummaryDto = { source_count: number, active_source_count: number, };

export type ClientsSnapshotDto = { generated_at_ms: number, client_cards: Array<ClientStatusCardDto>, sources: Array<ClientSourceRowDto>, next_cursor: string | null, summary: ClientsSnapshotSummaryDto, };

export type ClientSourceDetailRequestDto = { source_id: string, };

export type ClientSourceDetailDto = { source: ClientSourceRowDto, recent_activity: Array<ActivityListItemDto>, technical_details: Array<TechnicalDetailDto>, };

export type ManualRootDto = { id: string, client_id: string, root_path: string, source_type: SourceTypeDto, };

export type SettingsDiscoveryDto = { claude_code_default_paths: boolean, codex_default_paths: boolean, manual_roots: Array<ManualRootDto>, };

export type SettingsPrivacyDto = { local_only: boolean, redact_sensitive_values: boolean, };

export type SettingsDiagnosticsDto = { db_healthy: boolean, db_size_bytes: number, migration_version: number, usage_event_count: number, last_log_checkpoint_ms: number | null, 
/**
 * Current writer channel queue depth (0 = idle).
 */
writer_queue_depth: number, 
/**
 * Current aggregate lag in milliseconds (0 = caught up).
 */
aggregate_lag_ms: number, 
/**
 * Recent runtime diagnostic events (e.g. subscription lifecycle,
 * writer thresholds, drift events).
 */
recent_diagnostics: Array<SettingsDiagnosticEventDto>, 
/**
 * Subagent doctor checks (spec §7.1). `None` when the subagent feature
 * is disabled or not yet checked. Reuses the existing
 * `settings.diagnostics` RPC path — no separate `subagent.doctor` RPC.
 */
subagent: SubagentDoctorResultDto | null, };

export type SubagentDoctorResultDto = { checks: Array<DoctorCheckDto>, 
/**
 * True iff no check has `status == "error"`. Warnings don't fail.
 */
overall_ok: boolean, };

export type DoctorCheckDto = { name: string, status: string, detail: string | null, };

export type SettingsDiagnosticEventDto = { code: string, severity: string, message: string, happened_at_ms: number, };

export type SettingsRecoveryActionDto = { id: SettingsRecoveryActionIdDto, label: string, description: string, dangerous: boolean, };

export type SettingsRecoveryActionRequestDto = { id: SettingsRecoveryActionIdDto, };

export type SettingsRecoveryActionResponseDto = { id: SettingsRecoveryActionIdDto, accepted: boolean, message: string, };

export type SettingsValidationErrorDto = { code: SettingsValidationErrorCodeDto, field_path: string, message: string, };

export type SettingsSnapshotDto = { timezone: string, week_starts_on: WeekdayIndexDto, discovery: SettingsDiscoveryDto, privacy: SettingsPrivacyDto, diagnostics: SettingsDiagnosticsDto, recovery_actions: Array<SettingsRecoveryActionDto>, prompt_palette_default_action: PromptActionDto, };

export type SettingsUpdateRequestDto = { timezone: string | null, week_starts_on: WeekdayIndexDto | null, discovery: SettingsDiscoveryDto | null, privacy: SettingsPrivacyDto | null, prompt_palette_default_action: PromptActionDto | null, };

export type PromptActionDto = "OnlyCopy" | "OnlyPaste" | "CopyAndPaste";

export type PromptSortDto = "smart" | "recently_used" | "most_used" | "recently_updated" | "alphabetical" | "pinned_first";

export type PromptUseSurfaceDto = "overlay" | "page";

export type PromptUseOutcomeDto = "copy" | "paste_attempted" | "paste_fell_back_to_copy";

export type PromptUseFailureReasonDto = "permission_missing" | "focus_lost" | "injection_failed" | "unsupported_platform";

export type PromptEntryDto = { id: string, content: string, alias: string | null, tags: Array<string>, is_pinned: boolean, usage_count: number, last_used_at_ms: number | null, created_at_ms: number, updated_at_ms: number, };

export type PromptListQueryDto = { query: string | null, tag: string | null, sort: PromptSortDto | null, limit: number | null, };

export type PromptListResponseDto = { entries: Array<PromptEntryDto>, total_count: number, };

export type PromptGetRequestDto = { id: string, };

export type PromptCreateRequestDto = { content: string, alias: string | null, tags: Array<string>, };

export type PromptUpdateRequestDto = { id: string, content: string, alias: string | null, tags: Array<string>, is_pinned: boolean, };

export type PromptDeleteRequestDto = { id: string, };

export type PromptDeleteResultDto = { deleted: boolean, };

export type PromptUseRequestDto = { id: string, action: PromptActionDto, surface: PromptUseSurfaceDto, outcome: PromptUseOutcomeDto, failure_reason: PromptUseFailureReasonDto | null, };

export type PromptUseResultDto = { usage_count: number, last_used_at_ms: number | null, };

export type PromptSuggestTagsRequestDto = { query: string | null, limit: number | null, };

export type PromptSuggestTagsResponseDto = { tags: Array<string>, };

export type InvalidationDatasetDto = "overview" | "activity" | "clients" | "breakdown" | "settings" | "overview_summary" | "overview_trend" | "overview_heatmap" | "overview_rankings" | "activity_recent" | "activity_list" | "clients_snapshot" | "settings_diagnostics" | "diagnostics" | "live_realtime";

export type InvalidationScopeDto = { dataset: InvalidationDatasetDto, breakdown_kind: BreakdownKindDto | null, };

export type LiveSampleDto = { bucket_start_ms: number, tokens_per_sec: number, cost_per_sec: number | null, events_per_sec: number, };

export type ReadinessStateDto = "starting" | "rebuilding" | "ready_degraded" | "ready_exact";

export type ScanProgressDto = { scanned_files: number, total_files: number | null, current_path: string | null, elapsed_ms: number, };

export type ReadEnvelopeDto<T = JsonValue> = { data: T, generated_at_ms: number, generation_id: string | null, readiness: ReadinessStateDto, is_exact: boolean, is_stale: boolean, watermark_ms: number | null, progress: ScanProgressDto | null, degraded_reason: string | null, };

export type OverviewSummaryRequestDto = { range: RangePresetDto, };

export type OverviewSummaryDto = { timezone: string, selected_range: RangePresetDto, cost_status: CostStatusDto, metrics: Array<OverviewMetricDto>, generated_at_ms: number, };

export type OverviewTrendRequestDto = { range: RangePresetDto, granularity: TrendBucketGranularityDto | null, };

export type OverviewTrendResponseDto = { trend: OverviewTrendDto, };

export type OverviewHeatmapRequestDto = { range: RangePresetDto, };

export type OverviewHeatmapResponseDto = { heatmap: OverviewHeatmapDto, };

export type OverviewRankingsRequestDto = { range: RangePresetDto, };

export type OverviewRankingsResponseDto = { rankings: Array<OverviewRankingSectionDto>, };

export type ActivityRecentRequestDto = { range: RangePresetDto, limit: number | null, };

export type ActivityRecentResponseDto = { recent_activity: Array<ActivityListItemDto>, };

export type LiveWindowRequestDto = { window_seconds: number | null, };

export type LiveWindowDto = { 
/**
 * Exact samples from the active promoted generation (usage_buckets_2s).
 */
exact_samples: Array<LiveSampleDto>, 
/**
 * Transient samples from the in-memory ring buffer (available during
 * rebuild or first run before a generation is promoted).
 */
transient_samples: Array<LiveSampleDto>, current_tokens_per_sec: number, current_events_per_sec: number, start_ms: number, end_ms: number, };

export type EventSequenceStateDto = { last_event_id: number | null, sequence_gap: boolean, last_sequence_ms: number | null, };

export type RuntimeEventDto = { event_type: string, payload: JsonValue, 
/**
 * Global sequence number; None for ephemeral events.
 */
event_seq: number | null, 
/**
 * Whether this event is ephemeral (not checkpointed, not durable).
 */
ephemeral: boolean, 
/**
 * Invalidation scopes carried by the envelope.
 */
scopes: Array<InvalidationScopeDto>, 
/**
 * Generation ID at commit time.
 */
generation_id: string | null, 
/**
 * Watermark timestamp of the generation.
 */
watermark_ms: number | null, 
/**
 * Whether this event carries exact (committed / sampler) data.
 */
is_exact: boolean, };

export type EventSubscriptionBatchDto = { events: Array<RuntimeEventDto>, };

export type SubagentUsageDto = { model: string | null, provider: string | null, input_tokens: number | null, output_tokens: number | null, cache_read_tokens: number | null, cache_write_tokens: number | null, cost_usd: number | null, };

export type SubagentDelegateResponseDto = { task_id: string, subagent_id: string, subagent_name: string, adapter: string, adapter_session_id: string | null, session_reused: boolean, status: string, profile: string, model: string | null, summary: string | null, usage: SubagentUsageDto, };

export type SubagentResolveRequestDto = { name: string | null, id: string | null, cwd: string | null, };

export type SubagentDelegateRequestDto = { subagent_name: string, subagent_id: string | null, cwd: string, profile: string, intent: string | null, prompt: string, timeout_seconds: number | null, model_override: string | null, source_harness: string | null, source_session_id: string | null, };

export type SubagentListRequestDto = { 
/**
 * "hot" | "warm" | "cold"
 */
status: string | null, project: string | null, include_deleted: boolean | null, };

export type SubagentDetailDto = { id: string, name: string, project_id: string, repo_path: string, repo_hash: string, branch: string | null, intent: string | null, default_profile: string, default_model: string | null, status: string, created_at_ms: number, updated_at_ms: number, last_active_at_ms: number | null, };

export type SubagentListResponseDto = { subagents: Array<SubagentDetailDto>, };

export type SubagentTaskSummaryDto = { id: string, subagent_id: string, profile: string, status: string, prompt: string | null, result_summary: string | null, error: string | null, created_at_ms: number, completed_at_ms: number | null, };

export type SubagentTasksRequestDto = { name: string | null, id: string | null, cwd: string | null, limit: number | null, };

export type SubagentTasksResponseDto = { tasks: Array<SubagentTaskSummaryDto>, };

export type SubagentDeleteRequestDto = { name: string | null, id: string | null, cwd: string | null, hard: boolean | null, };

export type SubagentAckDto = { id: string, status: string, };
